title: "Alberto Muñoz-Ortiz"
description: ""
baseurl: ""
url: "https://amunozo.github.io"
theme: minima
markdown: kramdown

# Navigation links
header_pages:
  - research.md
  #- cv.md

# Social links
#twitter_username: amunozo
#github_username: amunozo
#linkedin_username: alberto-munoz-ortiz-683470106
#scholar_userid: sS5dz4QAAAAJ&hl

# Minima theme settings
#minima:
#  social_links:
#    twitter: amunozo
#    github: amunozo
#    linkedin: alberto-munoz-ortiz-683470106
#    google_scholar: sS5dz4QAAAAJ&hl