title: Alberto Muñoz-Ortiz
description: PhD student in Natural Language Processing at Universidade da Coruña

languages: ["es", "en"]
defaultLang: es
languageNames:
  es: Español
  en: English

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
theme: jekyll-theme-minimal
google_analytics: G-LSS8F0X3PE
markdown: kramdown
highlighter: rouge

include:
  - styles.css
