title: Alberto Muñoz-Ortiz
description: PhD student in NLP | Universidade da Coruña | alberto.munoz.ortiz (at) udc.es

languages: ["es", "en"]
defaultLang: es
languageNames:
  es: Español
  en: English

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-paginate # You may want to include this for blog pagination if needed
theme: jekyll-theme-minimal
google_analytics: G-LSS8F0X3PE
markdown: kramdown
highlighter: rouge

# Include specific files
include:
  - styles.css

# Define the navigation links
nav_links:
  - name: Home
    url: /
  - name: Blog
    url: /blog/
  - name: CV
    url: /cv/
  - name: Research
    url: /research/

# Blog settings (optional)
paginate: 5 # Number of posts per page if pagination is enabled
paginate_path: "/blog/page:num/"

