title: "Alberto Muñoz-Ortiz"
description: "Personal Website of Alberto Muñoz-Ortiz"
baseurl: "" 
url: "https://amunozo.github.io"
theme: minima
markdown: kramdown

# Navigation links
header_pages:
  - research.md
  - teaching.md
  - cv.md

# Social links (optional)
twitter_username: amunozo
github_username:  amunozo
linkedin_username: alberto-munoz-ortiz-683470106

# Google Analytics (optional)
# google_analytics: UA-NNNNNNNN-N

# Exclude files from processing
# exclude:
