title: "My Jekyll Site"
description: "A bilingual site in English and Spanish"
baseurl: ""  # or "/your-repo-name" if not using root
url: "https://amunozo.github.io"
theme: minima
markdown: kramdown

# Language settings
languages: 
  - en
  - es

# Collection for blog posts
collections:
  posts:
    output: true

# Navigation links
navbar:
  en:
    - title: "Home"
      url: /en/
  es:
    - title: "Inicio"
      url: /es/
