title: "My Jekyll Site"
description: "A bilingual site in English and Spanish"
baseurl: ""  # or "/your-repo-name" if not using root
url: "https://amunozo.github.io"
theme: minima
markdown: kramdown

# Language settings
languages: 
  - en
  - es

# Collection for blog posts
collections:
  posts:
    output: true

# Navigation links
navbar:
  en:
    - title: "Home"
      url: /en/
    <!-- - title: "CV"
      url: /en/cv
    - title: "Research"
      url: /en/research
    - title: "Blog"
      url: /en/blog
    - title: "About Me"
      url: /en/about -->
  es:
    - title: "Inicio"
      url: /es/
    <!-- - title: "CV"
      url: /es/cv
    - title: "Investigación"
      url: /es/research
    - title: "Blog"
      url: /es/blog
    - title: "Sobre Mí"
      url: /es/about -->

